### ISSUE TITLE
Run FTLsim

### ISSUE THREAD

**Issue by davidkmw0810** [ZiyangJiao/FTLSim#1]
Hello, I'm studying about FTL.
I want to follow you're paper, 'Wear Leveling in SSDs Considered Harmful'.
I'm already build FTLsim, but I cannot run the main code.

How can I simulate some wear leveling in FTLsim?

Thank you.

**Comment by ZiyangJiao** [comment]
Hi,

Please replace `ftlsim.c` file with one of the following files if you want to enable WL.

For example, `cp ftlsim_dp.c ftlsim.c` then compile.

[ftlsim_dp.c]: simulate dual pool WL
[ftlsim_dp_var.c]: simulate dual pool WL with capacity-variance
[ftlsim_op.c]: simulate old block protection WL
[ftlsim_op_var.c]: simulate old block protection WL with capacity-variance
[ftlsim_pwl.c]: simulate progressive WL 
[ftlsim_pwl_var.c]: simulate progressive WL with capacity-variance

Thank you.

**Comment by davidkmw0810** [comment]
Thank you for your answer.

I finshed build "ftlsim.c" copied by "ftlsim_dp.c".
When run python files(e.g., greedy-high.py, lru-high etc), it make segmentation fault.
Only low-level.py didn't make any error.
Is any wrong command I did?

This is my history
```bash
cp ftlsim_dp.c ftlsim.c
sudo python2 setup.py install
mv build/lib*/* .
python2 lru-high.py 
python2 lru-mixed
python2 greedy-high.py
```

RESULT:greedy-high.py
FTL T = 24880
ready...
**segmentation fault**

Thank you.

**Comment by ZiyangJiao** [comment]
Thank you for your comments.

These files needs to be executed under the original version of FTLSim without WL module enabled, which compiles with `ftlsim.c` [https://dl.acm.org/doi/10.1145/2577384]

To simulate WLs, please compile with corresponding files and use/modify the sample scripts under 'scripts' folder.

For example:
```
cp ftlsim_pwl.c ftlsim.c
python2 setup.py build && sudo python2 setup.py install
cd scripts
python2 pwl_skew_full.py
```

Please let me know if you have further questions.

**Comment by davidkmw0810** [comment]
Thank you for all you're answer.

When I followed your example, I have error ```AttributeError: 'module' object has no attribute 'ftl_swiginit'```
I think this error come from python version.
Python2.7 is used on my linux, am I have to change my version?

This is my error.
```Bash
$ python2 ./scripts/pwl_skew_full.py 
Traceback (most recent call last):
  File "./scripts/pwl_skew_full.py", line 70, in <module>
    ftl = ftlsim.ftl(T, Np)
  File "/usr/local/lib/python2.7/dist-packages/ftlsim.py", line 125, in __init__
    _ftlsim.ftl_swiginit(self, _ftlsim.new_ftl(T, Np))
AttributeError: 'module' object has no attribute 'ftl_swiginit'
```

Thank you for all your help.

**Comment by davidkmw0810** [comment]
Thank you for your help.

I followed your example. And I did work.
In last line ```python2 ./scripts/pwl_skew_full.py```, It just print
```Bash
$ python2 pwl_skew_full.py
re_ec_min: 0, 291527
ec_min: 291278, 291527
```
And its running is never end without interrupt.
This is right aciton with the python file?

Thank you.
